//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RiconApps_FASEntities1 : DbContext
    {
        public RiconApps_FASEntities1()
            : base("name=RiconApps_FASEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Install> Install { get; set; }
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<ReConfig> ReConfig { get; set; }
        public virtual DbSet<RMSC> RMSC { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
        public virtual DbSet<Tbl_Inwi> Tbl_Inwi { get; set; }
        public virtual DbSet<Tbl_Orange> Tbl_Orange { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<GsmNumber> GsmNumber { get; set; }
    }
}
