//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMSC
    {
        public int RMS_ID { get; set; }
        public Nullable<int> Device_Type_ID { get; set; }
        public string RMS_IP { get; set; }
        public string RMS_Port { get; set; }
        public Nullable<int> Company_ID { get; set; }
    }
}
