//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMCards3
    {
        public int SIM_ID { get; set; }
        public string GSM_No1 { get; set; }
        public string APN1_Name { get; set; }
        public string APN1_Username { get; set; }
        public string APN1_Password { get; set; }
        public string GSM_No2 { get; set; }
        public string APN2_Name { get; set; }
        public string APN2_Username { get; set; }
        public string APN2_Password { get; set; }
        public string Lan1_IP { get; set; }
        public string Lan1_SubnetMask { get; set; }
        public string Lan_Subnet { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string Ricon_SN { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
