//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inwi
    {
        public int Inwi_ID { get; set; }
        public string Ricon_SN { get; set; }
        public string GSM_No2 { get; set; }
        public string APN2_Name { get; set; }
        public string APN2_Username { get; set; }
        public string APN2_Password { get; set; }
        public string i_WAN_ip { get; set; }
        public string i_vlanid_TG { get; set; }
        public string i_lan_ip_TG { get; set; }
        public string i_lan_subnet_TG { get; set; }
        public string i_lan_subnetmask_TG { get; set; }
        public string i_vlanid_Servizi { get; set; }
        public string i_lan_ip_Servizi { get; set; }
        public string i_lan_subnet_Servizi { get; set; }
        public string i_lan_subnetmask_Servizi { get; set; }
        public Nullable<int> Status { get; set; }
        public string i_Tg_dhcp_start { get; set; }
        public string i_Tg_dhcp_end { get; set; }
        public string i_Ser_dhcp_start { get; set; }
        public string i_Ser_dhcp_end { get; set; }
    }
}
