//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNMPDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orange
    {
        public int Orange_ID { get; set; }
        public string Ricon_SN { get; set; }
        public string GSM_No1 { get; set; }
        public string APN1_Name { get; set; }
        public string APN1_Username { get; set; }
        public string APN1_Password { get; set; }
        public string WAN_ip { get; set; }
        public string vlanid_TG { get; set; }
        public string lan_ip_TG { get; set; }
        public string lan_subnet_TG { get; set; }
        public string lan_subnetmask_TG { get; set; }
        public string vlanid_Servizi { get; set; }
        public string lan_ip_Servizi { get; set; }
        public string lan_subnet_Servizi { get; set; }
        public string lan_subnetmask_Servizi { get; set; }
        public string Tunnel_dc1_r1 { get; set; }
        public string Tunnel_dc2_r1 { get; set; }
        public string Tunnel_ig_r1 { get; set; }
        public Nullable<int> Status { get; set; }
        public string Tg_dhcp_start { get; set; }
        public string Tg_dhcp_end { get; set; }
        public string Ser_dhcp_start { get; set; }
        public string Ser_dhcp_end { get; set; }
    }
}
