//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurulumWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KurulumWeb.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente.
        /// </summary>
        public static string L100 {
            get {
                return ResourceManager.GetString("L100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password d&apos;ordine.
        /// </summary>
        public static string L101 {
            get {
                return ResourceManager.GetString("L101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string L102 {
            get {
                return ResourceManager.GetString("L102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effettua il login con il tuo nome utente e password..
        /// </summary>
        public static string L103 {
            get {
                return ResourceManager.GetString("L103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM1.
        /// </summary>
        public static string L104 {
            get {
                return ResourceManager.GetString("L104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM2.
        /// </summary>
        public static string L105 {
            get {
                return ResourceManager.GetString("L105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricon S/N.
        /// </summary>
        public static string L106 {
            get {
                return ResourceManager.GetString("L106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS ID.
        /// </summary>
        public static string L107 {
            get {
                return ResourceManager.GetString("L107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il numero del sito.
        /// </summary>
        public static string L108 {
            get {
                return ResourceManager.GetString("L108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal ID/SN.
        /// </summary>
        public static string L109 {
            get {
                return ResourceManager.GetString("L109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvia.
        /// </summary>
        public static string L110 {
            get {
                return ResourceManager.GetString("L110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il numero GSM 1.
        /// </summary>
        public static string L111 {
            get {
                return ResourceManager.GetString("L111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il numero GSM 2.
        /// </summary>
        public static string L112 {
            get {
                return ResourceManager.GetString("L112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il numero di serie di Ricon.
        /// </summary>
        public static string L113 {
            get {
                return ResourceManager.GetString("L113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona ID terminale.
        /// </summary>
        public static string L114 {
            get {
                return ResourceManager.GetString("L114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di compilare tutti i campi richiesti e fare clic sul pulsante &quot;Avvia&quot;.
        /// </summary>
        public static string L115 {
            get {
                return ResourceManager.GetString("L115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente o password errati.
        /// </summary>
        public static string L116 {
            get {
                return ResourceManager.GetString("L116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di selezionare il numero GSM 1.
        /// </summary>
        public static string L117 {
            get {
                return ResourceManager.GetString("L117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di selezionare il numero GSM 2.
        /// </summary>
        public static string L118 {
            get {
                return ResourceManager.GetString("L118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di selezionare l&apos;ID del sito.
        /// </summary>
        public static string L119 {
            get {
                return ResourceManager.GetString("L119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di selezionare il Ricon S/N.
        /// </summary>
        public static string L120 {
            get {
                return ResourceManager.GetString("L120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di selezionare l&apos;ID del terminale.
        /// </summary>
        public static string L121 {
            get {
                return ResourceManager.GetString("L121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si prega di selezionare tutte le informazioni dall&apos;elenco.
        /// </summary>
        public static string L122 {
            get {
                return ResourceManager.GetString("L122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione!!! Il processo di installazione è già stato eseguito con il numero GSM che hai scelto..
        /// </summary>
        public static string L123 {
            get {
                return ResourceManager.GetString("L123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il processo di installazione è stato completato con successo, il tuo dispositivo si sta riavviando. Si prega di controllare gli indicatori a led del dispositivo. Puoi eseguire i test dopo il riavvio..
        /// </summary>
        public static string L124 {
            get {
                return ResourceManager.GetString("L124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il processo di installazione non è stato completato..
        /// </summary>
        public static string L125 {
            get {
                return ResourceManager.GetString("L125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizzare i dati.
        /// </summary>
        public static string L126 {
            get {
                return ResourceManager.GetString("L126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato Del Dispositivo.
        /// </summary>
        public static string L127 {
            get {
                return ResourceManager.GetString("L127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato di İnstallazione.
        /// </summary>
        public static string L128 {
            get {
                return ResourceManager.GetString("L128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data installazione ora.
        /// </summary>
        public static string L129 {
            get {
                return ResourceManager.GetString("L129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di serie Ricon.
        /// </summary>
        public static string L130 {
            get {
                return ResourceManager.GetString("L130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingegnera.
        /// </summary>
        public static string L131 {
            get {
                return ResourceManager.GetString("L131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome del sito.
        /// </summary>
        public static string L132 {
            get {
                return ResourceManager.GetString("L132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di serie del terminale.
        /// </summary>
        public static string L133 {
            get {
                return ResourceManager.GetString("L133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installato.
        /// </summary>
        public static string L134 {
            get {
                return ResourceManager.GetString("L134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non installato.
        /// </summary>
        public static string L135 {
            get {
                return ResourceManager.GetString("L135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivi Ricon.
        /// </summary>
        public static string L136 {
            get {
                return ResourceManager.GetString("L136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo installato.
        /// </summary>
        public static string L137 {
            get {
                return ResourceManager.GetString("L137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo rimanente.
        /// </summary>
        public static string L138 {
            get {
                return ResourceManager.GetString("L138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valore.
        /// </summary>
        public static string L139 {
            get {
                return ResourceManager.GetString("L139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIM GSM Numero.
        /// </summary>
        public static string L140 {
            get {
                return ResourceManager.GetString("L140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinTre GSM Numero.
        /// </summary>
        public static string L141 {
            get {
                return ResourceManager.GetString("L141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sito.
        /// </summary>
        public static string L142 {
            get {
                return ResourceManager.GetString("L142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa grafico.
        /// </summary>
        public static string L143 {
            get {
                return ResourceManager.GetString("L143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica il documento PDF.
        /// </summary>
        public static string L144 {
            get {
                return ResourceManager.GetString("L144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica il documento PNG.
        /// </summary>
        public static string L145 {
            get {
                return ResourceManager.GetString("L145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore!.
        /// </summary>
        public static string L200 {
            get {
                return ResourceManager.GetString("L200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvertimento!.
        /// </summary>
        public static string L201 {
            get {
                return ResourceManager.GetString("L201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermare.
        /// </summary>
        public static string L203 {
            get {
                return ResourceManager.GetString("L203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudere.
        /// </summary>
        public static string L204 {
            get {
                return ResourceManager.GetString("L204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai scelto la SIM 2.
        /// </summary>
        public static string L205 {
            get {
                return ResourceManager.GetString("L205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il router Ricon che stai per attivare viene utilizzato in precedenza su un altro sito. Il nome e i parametri del sito precedente verranno cancellati/aggiornati con le nuove impostazioni del sito correnti. Si prega di confermare?.
        /// </summary>
        public static string L210 {
            get {
                return ResourceManager.GetString("L210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il numero di serie Ricon attualmente selezionato e l&apos;ID POS sono individualmente esistenti nel database di installazione. I parametri selezionati non sono corretti.
        ///Innanzitutto assicurati che Ricon S/N e POS ID con l&apos;ingegnere sul campo. In caso contrario, contattare il proprio supervisore o cambiare il dispositivo Ricon con un numero di serie diverso per procedere.
        ///Si prega di restituire il dispositivo Ricon al magazzino per scopi di RMA. Non utilizzare questo dispositivo per nessun&apos;altra installazione..
        /// </summary>
        public static string L211 {
            get {
                return ResourceManager.GetString("L211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo sito che stai attivando attualmente è stato attivato con un altro dispositivo Ricon in precedenza. Il numero di serie Ricon associato a questo ID POS verrà aggiornato con la sostituzione. Confermare? Nota: accedere a RMSC e aggiornare lo stato del dispositivo Ricon sostitutivo su: Sostituito / Difettoso.
        /// </summary>
        public static string L212 {
            get {
                return ResourceManager.GetString("L212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica Ipsec Fase12 NON CONSEGNATA 
        ///L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///L&apos;Antenna 2 (l&apos;Antenna con cavo da 2,5mt. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L220 {
            get {
                return ResourceManager.GetString("L220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica Ipsec Fase12 inviato con successo.
        /// </summary>
        public static string L221 {
            get {
                return ResourceManager.GetString("L221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica Ipsec Fase22 NON CONSEGNATA  L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///     L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///     L&apos;Antenna 2 (l&apos;Antenna con cavo d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L222 {
            get {
                return ResourceManager.GetString("L222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica Ipsec Fase22 inviato con successo.
        /// </summary>
        public static string L223 {
            get {
                return ResourceManager.GetString("L223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impostazioni lan NON CONSEGNATO  
        ///L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///L&apos;Antenna 2 (l&apos;Antenna con cavo da 2,5mt.) de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L224 {
            get {
                return ResourceManager.GetString("L224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impostazioni lan Messaggio inviato con successo.
        /// </summary>
        public static string L225 {
            get {
                return ResourceManager.GetString("L225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM1 NON CONSEGNATO
        ///L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///L&apos;Antenna 2 (l&apos;Antenna con cavo da 2,5mt.) deve essere coll [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L226 {
            get {
                return ResourceManager.GetString("L226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM1 Messaggio inviato con successo.
        /// </summary>
        public static string L227 {
            get {
                return ResourceManager.GetString("L227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM2 NON CONSEGNATO 
        ///L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///L&apos;Antenna 2 (l&apos;Antenna con cavo da 2,5mt.) deve essere col [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L228 {
            get {
                return ResourceManager.GetString("L228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM2 Messaggio inviato con successo.
        /// </summary>
        public static string L229 {
            get {
                return ResourceManager.GetString("L229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup del collegamento NON CONSEGNATA      
        ///L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///L&apos;Antenna 2 (l&apos;Antenna con cavo da [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L230 {
            get {
                return ResourceManager.GetString("L230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup del collegamento Messaggio inviato con successo.
        /// </summary>
        public static string L231 {
            get {
                return ResourceManager.GetString("L231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavviare NON CONSEGNATO  
        ///L&apos;installazione non può essere eseguita a causa di una situazione anomala. Si prega di controllare e confermare attentamente i seguenti elementi con il tecnico del sito:
        ///A. Assicurati che il dispositivo sia acceso e che i LED di stato lampeggino in arancione.
        ///B. Controllare i 2 connettori delle antenne dati se collegati ai connettori SMA corretti:
        ///L&apos;Antenna 1 (l&apos;Antenna con cavo da 2,5mt.) deve essere collegata alla Porta 4G-1
        ///L&apos;Antenna 2 (l&apos;Antenna con cavo da 2,5mt.) deve esse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string L232 {
            get {
                return ResourceManager.GetString("L232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riavviare Messaggio inviato con successo.
        /// </summary>
        public static string L233 {
            get {
                return ResourceManager.GetString("L233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore imprevisto. Riavvia il sistema..
        /// </summary>
        public static string L234 {
            get {
                return ResourceManager.GetString("L234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not perform Activation! Check Router Signal!.
        /// </summary>
        public static string L235 {
            get {
                return ResourceManager.GetString("L235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun segnale rilevato. Controllare le antenne, riavviare il dispositivo e riprovare l&apos;attivazione..
        /// </summary>
        public static string L236 {
            get {
                return ResourceManager.GetString("L236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica Ipsec Fase21 ikev1 inviato con successo.
        /// </summary>
        public static string L237 {
            get {
                return ResourceManager.GetString("L237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politica Ipsec Fase21 ikev1 NON CONSEGNATA.
        /// </summary>
        public static string L238 {
            get {
                return ResourceManager.GetString("L238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiamo avviando l&apos;installazione, confermi?.
        /// </summary>
        public static string L239 {
            get {
                return ResourceManager.GetString("L239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricare.
        /// </summary>
        public static string L240 {
            get {
                return ResourceManager.GetString("L240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string L241 {
            get {
                return ResourceManager.GetString("L241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione SIM.
        /// </summary>
        public static string L242 {
            get {
                return ResourceManager.GetString("L242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatta.
        /// </summary>
        public static string L243 {
            get {
                return ResourceManager.GetString("L243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagine.
        /// </summary>
        public static string L244 {
            get {
                return ResourceManager.GetString("L244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importazione in blocco(Posizione).
        /// </summary>
        public static string L245 {
            get {
                return ResourceManager.GetString("L245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica Orange.
        /// </summary>
        public static string L246 {
            get {
                return ResourceManager.GetString("L246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione della distribuzione.
        /// </summary>
        public static string L247 {
            get {
                return ResourceManager.GetString("L247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticazione.
        /// </summary>
        public static string L248 {
            get {
                return ResourceManager.GetString("L248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica tabella.
        /// </summary>
        public static string L249 {
            get {
                return ResourceManager.GetString("L249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione.
        /// </summary>
        public static string L250 {
            get {
                return ResourceManager.GetString("L250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voci di sottomenu.
        /// </summary>
        public static string L251 {
            get {
                return ResourceManager.GetString("L251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestisci siti.
        /// </summary>
        public static string L252 {
            get {
                return ResourceManager.GetString("L252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importazione in blocco (Orange&amp;Inwi).
        /// </summary>
        public static string L253 {
            get {
                return ResourceManager.GetString("L253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnessione.
        /// </summary>
        public static string L254 {
            get {
                return ResourceManager.GetString("L254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RICONAPPS ZERO TOUCH PROVISIONING.
        /// </summary>
        public static string L255 {
            get {
                return ResourceManager.GetString("L255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli Paese.
        /// </summary>
        public static string L256 {
            get {
                return ResourceManager.GetString("L256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riservatezza.
        /// </summary>
        public static string L257 {
            get {
                return ResourceManager.GetString("L257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condizioni.
        /// </summary>
        public static string L258 {
            get {
                return ResourceManager.GetString("L258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Siamo.
        /// </summary>
        public static string L259 {
            get {
                return ResourceManager.GetString("L259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo File Aggiungi.
        /// </summary>
        public static string L260 {
            get {
                return ResourceManager.GetString("L260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string L261 {
            get {
                return ResourceManager.GetString("L261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trascina e rilascia il tuo file qui.
        /// </summary>
        public static string L262 {
            get {
                return ResourceManager.GetString("L262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica.
        /// </summary>
        public static string L263 {
            get {
                return ResourceManager.GetString("L263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string L264 {
            get {
                return ResourceManager.GetString("L264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfogliare.
        /// </summary>
        public static string L265 {
            get {
                return ResourceManager.GetString("L265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricamento riuscito.
        /// </summary>
        public static string L266 {
            get {
                return ResourceManager.GetString("L266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricamento non riuscito.
        /// </summary>
        public static string L267 {
            get {
                return ResourceManager.GetString("L267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il caricamento del file:.
        /// </summary>
        public static string L268 {
            get {
                return ResourceManager.GetString("L268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo di attivazione del router.
        /// </summary>
        public static string L269 {
            get {
                return ResourceManager.GetString("L269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo di modifica del router.
        /// </summary>
        public static string L270 {
            get {
                return ResourceManager.GetString("L270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento.
        /// </summary>
        public static string L271 {
            get {
                return ResourceManager.GetString("L271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Azure..
        /// </summary>
        public static string L272 {
            get {
                return ResourceManager.GetString("L272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string L273 {
            get {
                return ResourceManager.GetString("L273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona Nome sito ...
        /// </summary>
        public static string L274 {
            get {
                return ResourceManager.GetString("L274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installazione completata.
        /// </summary>
        public static string L275 {
            get {
                return ResourceManager.GetString("L275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progetto Router totale.
        /// </summary>
        public static string L276 {
            get {
                return ResourceManager.GetString("L276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungere.
        /// </summary>
        public static string L277 {
            get {
                return ResourceManager.GetString("L277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminare.
        /// </summary>
        public static string L278 {
            get {
                return ResourceManager.GetString("L278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string L279 {
            get {
                return ResourceManager.GetString("L279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string L280 {
            get {
                return ResourceManager.GetString("L280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona un file..
        /// </summary>
        public static string L281 {
            get {
                return ResourceManager.GetString("L281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il caricamento è riuscito.
        /// </summary>
        public static string L282 {
            get {
                return ResourceManager.GetString("L282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File caricato:.
        /// </summary>
        public static string L283 {
            get {
                return ResourceManager.GetString("L283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il caricamento non è riuscito.
        /// </summary>
        public static string L284 {
            get {
                return ResourceManager.GetString("L284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il caricamento del file:.
        /// </summary>
        public static string L285 {
            get {
                return ResourceManager.GetString("L285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore trovato nelle righe:.
        /// </summary>
        public static string L286 {
            get {
                return ResourceManager.GetString("L286", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Righe non caricate:.
        /// </summary>
        public static string L287 {
            get {
                return ResourceManager.GetString("L287", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler avviare il processo di attivazione?.
        /// </summary>
        public static string L289 {
            get {
                return ResourceManager.GetString("L289", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma del processo di installazione.
        /// </summary>
        public static string L290 {
            get {
                return ResourceManager.GetString("L290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il processo di attivazione è stato avviato, non chiudere questa pagina fino al termine..
        /// </summary>
        public static string L291 {
            get {
                return ResourceManager.GetString("L291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        public static string L292 {
            get {
                return ResourceManager.GetString("L292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le informazioni sulla posizione verranno eliminate. Confermi?.
        /// </summary>
        public static string L293 {
            get {
                return ResourceManager.GetString("L293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string L294 {
            get {
                return ResourceManager.GetString("L294", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome della nuova posizione:.
        /// </summary>
        public static string L295 {
            get {
                return ResourceManager.GetString("L295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiunta di una nuova posizione.
        /// </summary>
        public static string L296 {
            get {
                return ResourceManager.GetString("L296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nuova posizione è stata salvata con successo..
        /// </summary>
        public static string L297 {
            get {
                return ResourceManager.GetString("L297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La posizione è stata eliminata con successo..
        /// </summary>
        public static string L298 {
            get {
                return ResourceManager.GetString("L298", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transazione riuscita.
        /// </summary>
        public static string L299 {
            get {
                return ResourceManager.GetString("L299", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importazione in blocco (numero di serie).
        /// </summary>
        public static string L300 {
            get {
                return ResourceManager.GetString("L300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica numero di serie.
        /// </summary>
        public static string L301 {
            get {
                return ResourceManager.GetString("L301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarica il Template.
        /// </summary>
        public static string L302 {
            get {
                return ResourceManager.GetString("L302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELEZIONARE IL NUMERO DI GSM..
        /// </summary>
        public static string L303 {
            get {
                return ResourceManager.GetString("L303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza i dati.
        /// </summary>
        public static string L304 {
            get {
                return ResourceManager.GetString("L304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato del progetto in tempo reale.
        /// </summary>
        public static string L305 {
            get {
                return ResourceManager.GetString("L305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi un nuovo Sim.
        /// </summary>
        public static string L306 {
            get {
                return ResourceManager.GetString("L306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I dati della sim saranno cancellati. Siete d&apos;accordo?.
        /// </summary>
        public static string L307 {
            get {
                return ResourceManager.GetString("L307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le informazioni sul numero di serie vengono eliminate. Siete d&apos;accordo?.
        /// </summary>
        public static string L308 {
            get {
                return ResourceManager.GetString("L308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le informazioni sulla sim sono state eliminate con successo..
        /// </summary>
        public static string L309 {
            get {
                return ResourceManager.GetString("L309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le informazioni del Sim sono state memorizzate con successo..
        /// </summary>
        public static string L310 {
            get {
                return ResourceManager.GetString("L310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungere un nuovo numero di serie.
        /// </summary>
        public static string L311 {
            get {
                return ResourceManager.GetString("L311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il nuovo numero di serie è stato registrato con successo..
        /// </summary>
        public static string L312 {
            get {
                return ResourceManager.GetString("L312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il numero di serie è stato cancellato con successo..
        /// </summary>
        public static string L313 {
            get {
                return ResourceManager.GetString("L313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conti.
        /// </summary>
        public static string L314 {
            get {
                return ResourceManager.GetString("L314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare il numero GSM.
        /// </summary>
        public static string L315 {
            get {
                return ResourceManager.GetString("L315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare Gsm No.
        /// </summary>
        public static string L316 {
            get {
                return ResourceManager.GetString("L316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione dei conti.
        /// </summary>
        public static string L317 {
            get {
                return ResourceManager.GetString("L317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestire Azure AD.
        /// </summary>
        public static string L318 {
            get {
                return ResourceManager.GetString("L318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizzare la contabilità.
        /// </summary>
        public static string L319 {
            get {
                return ResourceManager.GetString("L319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi nuovo record.
        /// </summary>
        public static string L320 {
            get {
                return ResourceManager.GetString("L320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi nuovi dati arancioni.
        /// </summary>
        public static string L321 {
            get {
                return ResourceManager.GetString("L321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accettate che le Informazioni sui dati di Orange vengano cancellate?.
        /// </summary>
        public static string L322 {
            get {
                return ResourceManager.GetString("L322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungere nuovi dati Inwi.
        /// </summary>
        public static string L323 {
            get {
                return ResourceManager.GetString("L323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acconsente alla cancellazione dei dati Inwi?.
        /// </summary>
        public static string L324 {
            get {
                return ResourceManager.GetString("L324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo di modifica dei dati arancioni.
        /// </summary>
        public static string L325 {
            get {
                return ResourceManager.GetString("L325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo di organizzazione dei dati Inwi.
        /// </summary>
        public static string L326 {
            get {
                return ResourceManager.GetString("L326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo per la disposizione dei numeri di serie.
        /// </summary>
        public static string L327 {
            get {
                return ResourceManager.GetString("L327", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo per l&apos;organizzazione della sede.
        /// </summary>
        public static string L328 {
            get {
                return ResourceManager.GetString("L328", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange I dati sono stati cancellati con successo..
        /// </summary>
        public static string L329 {
            get {
                return ResourceManager.GetString("L329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arancione I dati sono stati registrati con successo..
        /// </summary>
        public static string L330 {
            get {
                return ResourceManager.GetString("L330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I dati Inwi sono stati eliminati con successo..
        /// </summary>
        public static string L331 {
            get {
                return ResourceManager.GetString("L331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inwi I dati sono stati registrati con successo..
        /// </summary>
        public static string L332 {
            get {
                return ResourceManager.GetString("L332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confermate che le informazioni dell&apos;utente selezionato saranno cancellate?.
        /// </summary>
        public static string L333 {
            get {
                return ResourceManager.GetString("L333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo record aggiunto con successo..
        /// </summary>
        public static string L334 {
            get {
                return ResourceManager.GetString("L334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le informazioni dell&apos;utente selezionato sono state eliminate con successo..
        /// </summary>
        public static string L335 {
            get {
                return ResourceManager.GetString("L335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni.
        /// </summary>
        public static string L336 {
            get {
                return ResourceManager.GetString("L336", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica dati Inwi.
        /// </summary>
        public static string L337 {
            get {
                return ResourceManager.GetString("L337", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è conforme ai requisiti di sicurezza della password. La password deve contenere un minimo di 8 caratteri, almeno una lettera maiuscola, un simbolo e un numero..
        /// </summary>
        public static string L338 {
            get {
                return ResourceManager.GetString("L338", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivato con..
        /// </summary>
        public static string L339 {
            get {
                return ResourceManager.GetString("L339", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona solo un tipo di file (Inwi o Orange)..
        /// </summary>
        public static string L340 {
            get {
                return ResourceManager.GetString("L340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File non selezionato..
        /// </summary>
        public static string L341 {
            get {
                return ResourceManager.GetString("L341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi lotto (utente).
        /// </summary>
        public static string L342 {
            get {
                return ResourceManager.GetString("L342", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente.
        /// </summary>
        public static string L343 {
            get {
                return ResourceManager.GetString("L343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string L344 {
            get {
                return ResourceManager.GetString("L344", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string L345 {
            get {
                return ResourceManager.GetString("L345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatore.
        /// </summary>
        public static string L346 {
            get {
                return ResourceManager.GetString("L346", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creare DateTime.
        /// </summary>
        public static string L347 {
            get {
                return ResourceManager.GetString("L347", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esportazione dei dati.
        /// </summary>
        public static string L348 {
            get {
                return ResourceManager.GetString("L348", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante la creazione del file Excel:.
        /// </summary>
        public static string L349 {
            get {
                return ResourceManager.GetString("L349", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettaglio Dati Orange.
        /// </summary>
        public static string L350 {
            get {
                return ResourceManager.GetString("L350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettaglio Dati Inwi.
        /// </summary>
        public static string L351 {
            get {
                return ResourceManager.GetString("L351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Va bene..
        /// </summary>
        public static string L352 {
            get {
                return ResourceManager.GetString("L352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il numero GSM selezionato manca nei modelli Orange o Inwi. Contattare il proprio supervisore..
        /// </summary>
        public static string L353 {
            get {
                return ResourceManager.GetString("L353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova registrazione fallita.
        ///Il numero Gsm inserito esiste già nella tabella Inwi..
        /// </summary>
        public static string L354 {
            get {
                return ResourceManager.GetString("L354", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuova registrazione fallita.
        ///Il numero Gsm inserito esiste già nella tabella arancione..
        /// </summary>
        public static string L355 {
            get {
                return ResourceManager.GetString("L355", resourceCulture);
            }
        }
    }
}
